from app.plugins import (  # noqa: F401  (import triggers self-registration)
    birch_plugin,
    dbscan_plugin,
    gmm_plugin,
    gradient_boosting_classifier_plugin,
    gradient_boosting_regressor_plugin,
    hierarchical_plugin,
    kmeans_plugin,
    knn_classifier_plugin,
    knn_regressor_plugin,
    linear_regression_plugin,
    logistic_regression_plugin,
    optics_plugin,
    random_forest_classifier_plugin,
    random_forest_regressor_plugin,
    spectral_plugin,
    svm_classifier_plugin,
    svr_plugin,
)
from app.plugins.registry import (
    CLASSIFICATION_PLUGIN_REGISTRY,
    PLUGIN_REGISTRY,
    REGRESSION_PLUGIN_REGISTRY,
    get_classification_plugin,
    get_plugin,
    get_regression_plugin,
    register_classification_plugin,
    register_plugin,
    register_regression_plugin,
)

__all__ = [
    "PLUGIN_REGISTRY",
    "CLASSIFICATION_PLUGIN_REGISTRY",
    "REGRESSION_PLUGIN_REGISTRY",
    "get_plugin",
    "get_classification_plugin",
    "get_regression_plugin",
    "register_plugin",
    "register_classification_plugin",
    "register_regression_plugin",
]
